environment: development

apphost: k8s

label:
  name: aspnet3core

container:
  name: aspnet3
  pullPolicy: IfNotPresent
  image: apipock8s
  tag: 0.0.0.1
  port: 80
replicas: 3

service:
  port: 8888
  type: ClusterIP