environment: development

apphost: apipock8s

label:
  name: apipock8s

container:
  name: apipock8s
  pullPolicy: IfNotPresent
  image: apipock8s
  tag: 0.0.1
  port: 80
replicas: 3

service:
  port: 8888
  type: NodePort
  nodeport: 31348

ingress:
  rules:
    host: localhost

hpa:
  maxReplicas: 10
  minReplicas: 1